apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: antifraud-online
  namespace: antifraud-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: antifraud.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: antifraud-online
                port:
                  number: 80
