apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: antifraud-system

resources:
  - namespace.yaml
  - configmap.yaml
  # secret.yaml and airflow-secrets.yaml are managed by k8s_deploy.sh
  - minio-pvc.yaml
  - minio-deployment.yaml
  - minio-service.yaml
  - online-deployment.yaml
  - online-service.yaml
  - online-hpa.yaml
  - batch-cronjob.yaml
  - ingress.yaml
  - airflow-configmap.yaml
  - airflow-dags-configmap.yaml
  - airflow-db.yaml
  - airflow-logs-pvc.yaml
  - airflow-rbac.yaml
  - airflow-scheduler.yaml
  - airflow-webserver.yaml

images:
  - name: antifraud-online
    newName: ghcr.io/shadxwkxw/antifraud-online
    newTag: latest
  - name: antifraud-batch
    newName: ghcr.io/shadxwkxw/antifraud-batch
    newTag: latest
  - name: antifraud-airflow
    newName: ghcr.io/shadxwkxw/antifraud-airflow
    newTag: latest
