services:
  antifraud-online:
    build:
      context: .
      dockerfile: services/online/Dockerfile
    container_name: antifraud-online
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - antifraud-network

  postgres:
    image: postgres:15
    container_name: antifraud-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AIRFLOW_DB_NAME: ${AIRFLOW_DB_NAME}
      AIRFLOW_DB_USER: ${AIRFLOW_DB_USER}
      AIRFLOW_DB_PASSWORD: ${AIRFLOW_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/antifraud/infrastructure/storage/01-create-airflow-db.sh:/docker-entrypoint-initdb.d/01-create-airflow-db.sh
    networks:
      - antifraud-network

  airflow:
    build:
      context: .
      dockerfile: ./airflow/Dockerfile
    image: airflow-local:latest
    container_name: airflow
    entrypoint: /bin/bash -c "airflow db migrate && airflow users create --username $${_AIRFLOW_WWW_USER_USERNAME} --password $${_AIRFLOW_WWW_USER_PASSWORD} --firstname Airflow --lastname User --role Admin --email airflow@example.com || true && airflow standalone"
    env_file:
      - .env
    ports:
      - "${AIRFLOW_WEBSERVER_PORT}:${AIRFLOW_WEBSERVER_PORT}"
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__AUTHENTICATE: 'true'
      AIRFLOW__WEBSERVER__AUTH_BACKEND: 'airflow.www.security:init_appbuilder_views'
      AIRFLOW__WEBSERVER__RBAC: 'true'
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: ${AIRFLOW_WEBSERVER_PORT}
    volumes:
      - ./src/antifraud/interfaces/batch/dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
      - ./airflow/logs:/opt/airflow/logs
      - ./configs:/app/configs
      - ./data:/app/data
      - ./models:/app/models
      - ./src:/opt/airflow/src
    depends_on:
      - postgres
    networks:
      - antifraud-network


networks:
  antifraud-network:
    name: antifraud-network
    driver: bridge

volumes:
  postgres_data:
